### ISSUE TITLE
你好, oppo反馈调用相册 选择微信分身保存的图片失败呢

### ISSUE THREAD

**Issue by badboy-tian** [LwkCoder/ImagePicker#23]
![image](https://user-images.githubusercontent.com/2835129/148377627-a45e457b-17d2-437f-b519-ffc2747eddb0.png)

![image](https://user-images.githubusercontent.com/2835129/148377735-49609b75-7b8b-441e-834d-d64f5cf50744.png)

**Comment by badboy-tian** [comment]
需要提供什么其他的, 我这边可以提供呢

**Comment by badboy-tian** [comment]
Reno7 android 11 

https://open.oppomobile.com/newservice/capability?pagename=cloudmachine（这是OPPO云测地址）可以用上传包的账号密码登录，或个人注册账号登录

**Comment by badboy-tian** [comment]
![b93a9870d678582c3c47579309bb9e4](https://user-images.githubusercontent.com/2835129/148381088-153e39fc-f2d2-4f89-9880-8ce591902ec0.png)
分身的图片是保存在这个路径的

**Comment by badboy-tian** [comment]
![b93a9870d678582c3c47579309bb9e4](https://user-images.githubusercontent.com/2835129/148381141-d9996713-9a60-4c90-9bcf-67ed7b955cfa.png)
分身的图片是保存在这个路径的

**Comment by badboy-tian** [comment]
com.lwkandroid.imagepicker.ui.grid.view.ImageDataActivity  这个activity里面显示微信分身保存的图片是空的?

**Comment by badboy-tian** [comment]
小米手机测试没问题 就oppo vivo手机

**Comment by badboy-tian** [comment]
![image](https://user-images.githubusercontent.com/2835129/148410235-118aa4b2-9e0b-4ede-a679-b5d30007df41.png)
出问题这个 图片路径为什么不是storyage/emulated/0/呢?

**Comment by badboy-tian** [comment]
![image](https://user-images.githubusercontent.com/2835129/148486382-5ff9c51b-b4e3-4739-8105-69a9a7473084.png)

**Comment by Vanish136** [comment]
不好意思哥们  我已经不做开发了  可能需要你自己从源码里排查原因啦

**Comment by badboy-tian** [comment]
好的~谢谢
